// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID    int32
	Email string
}
