// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type User struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

type Workspace struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Owner int32  `json:"owner"`
}
