// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email) VALUES ($1)
`

func (q *Queries) CreateUser(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, createUser, email)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, owner) VALUES ($1, $2) RETURNING id, name, owner
`

type CreateWorkspaceParams struct {
	Name  string `json:"name"`
	Owner int32  `json:"owner"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Owner)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.Owner)
	return i, err
}

const findUserWithEmail = `-- name: FindUserWithEmail :one
SELECT id, email FROM users WHERE email = $1
`

func (q *Queries) FindUserWithEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserWithEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const findUserWithId = `-- name: FindUserWithId :one
SELECT id, email FROM users WHERE id = $1
`

func (q *Queries) FindUserWithId(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, findUserWithId, id)
	var i User
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const listUserWorkspaces = `-- name: ListUserWorkspaces :many
SELECT id, name, owner FROM workspaces WHERE owner = $1
`

func (q *Queries) ListUserWorkspaces(ctx context.Context, owner int32) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listUserWorkspaces, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(&i.ID, &i.Name, &i.Owner); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
