apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    k8s-app: api
spec:
  selector:
    matchLabels:
      k8s-app: api
  template:
    metadata:
      labels:
        k8s-app: api
    spec:
      containers:
      - name: api
        image: web-client/api
        resources:
          limits:
            memory: 1Gi
            cpu: 1
        ports:
        - containerPort: 8090
        env:
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: ENV
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: PORT
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: OAUTH_CLIENT_ID
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: OAUTH_CLIENT_SECRET
        - name: OAUTH_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: OAUTH_CALLBACK_URL
        - name: ISSUER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: ISSUER
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: API_URL
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DOMAIN
        - name: APP_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: APP_URL
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_URL
        - name: KUBE_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: KUBE_TOKEN
        - name: KUBE_CERT
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: KUBE_CERT
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace